---
- name: Set the system shortname
  copy: content="{{ short_name }}\n" dest=/etc/hostname owner=root group=root
        mode=0644
  notify: restart hostname service

- name: Updates /etc/hosts to map fqdn to IP address
  lineinfile: dest=/etc/hosts regexp="^{{ ip_address }}" line="{{ etc_hosts_entry }}"
              state=present
  notify: restart hostname service
