---
- name: Generate locale
  command: /usr/sbin/locale-gen {{ locale }}
  changed_when: False

- name: Set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  changed_when: False

- name: Ensures we have the latest timezone data
  apt: name=tzdata state=latest

- name: Ensures correct timezone description is set
  copy: content="{{ timezone }}\n" dest=/etc/timezone owner=root group=root
        mode=0644
  notify: update timezone  
