- name: Remove sudo group authorizations
  lineinfile: dest=/etc/sudoers regexp=^% state=absent validate='visudo -cf %s'

- name: Remove included directory for additional sudo configuration
  lineinfile: dest=/etc/sudoers regexp=^includeddir state=absent validate='visudo -cf %s'

- name: Delete /etc/sudoers.d/ files
  file: path=/etc/sudoers.d/* state=absent
