---
- name: restart sshd
  service: name=ssh state=restarted

- name: restart hostname service
  service: name=hostname state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart firewall
  service: name={{ item }} state=restarted
  with_items:
    - firewall
    - fail2ban
